FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

SHELL ["/bin/bash", "-lc"]

COPY environment.aio_qc.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml && \
    /opt/conda/bin/conda clean -a -y

ENV CONDA_DEFAULT_ENV=aio_qc
ENV CONDA_PREFIX=/opt/conda/envs/aio_qc
ENV PATH=/opt/conda/envs/aio_qc/bin:/opt/conda/bin:$PATH

CMD ["bash"]
