FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2
LABEL org.opencontainers.image.source="https://github.com/BDRD-Genomics/All_In_One"

SHELL ["/bin/bash", "-lc"]

COPY environment.multiqc.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml && \
    /opt/conda/bin/conda clean -a -y

ENV CONDA_DEFAULT_ENV=multiqc
ENV CONDA_PREFIX=/opt/conda/envs/multiqc
ENV PATH=/opt/conda/envs/multiqc/bin:/opt/conda/bin:$PATH

CMD ["bash"]
