FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

LABEL org.opencontainers.image.source="https://github.com/BDRD-Genomics/All_In_One"
LABEL org.opencontainers.image.title="All_In_One checkv"

SHELL ["/bin/bash", "-lc"]

COPY environment.checkv.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml \
    && /opt/conda/bin/mamba clean -a -y \
    && /opt/conda/bin/conda clean -a -y \
    && rm -rf /opt/conda/pkgs/* /root/.cache /tmp/* /var/tmp/*

ENV CONDA_DEFAULT_ENV=checkv
ENV CONDA_PREFIX=/opt/conda/envs/checkv
ENV PATH=/opt/conda/envs/checkv/bin:/opt/conda/bin:$PATH

CMD ["bash"]
