FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

SHELL ["/bin/bash", "-lc"]

COPY environment.chimeric.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml && \
    /opt/conda/bin/conda clean -a -y

ENV CONDA_DEFAULT_ENV=chimeric
ENV CONDA_PREFIX=/opt/conda/envs/chimeric
ENV PATH=/opt/conda/envs/chimeric/bin:/opt/conda/bin:$PATH
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# ETE3 taxonomy path expected by the script:
# /home/edge/.etetoolkit/taxa.sqlite
RUN mkdir -p /home/edge/.etetoolkit

CMD ["bash"]
