FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

SHELL ["/bin/bash", "-lc"]

COPY environment.unicycler.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml && \
    /opt/conda/bin/conda clean -a -y

ENV CONDA_DEFAULT_ENV=unicycler
ENV CONDA_PREFIX=/opt/conda/envs/unicycler
ENV PATH=/opt/conda/envs/unicycler/bin:/opt/conda/bin:$PATH

CMD ["bash"]
