FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2
LABEL org.opencontainers.image.source="https://github.com/BDRD-Genomics/All_In_One"

COPY environment.python_reports.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -n python_reports -f /tmp/environment.yml \
    && /opt/conda/bin/conda clean -afy \
    && rm -f /tmp/environment.yml

ENV PATH=/opt/conda/envs/python_reports/bin:$PATH
SHELL ["/bin/bash", "-lc"]
