FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

LABEL org.opencontainers.image.source="https://github.com/BDRD-Genomics/All_In_One"

SHELL ["/bin/bash", "-lc"]

ARG ENV_FILE
ARG ENV_NAME
COPY ${ENV_FILE} /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml \
    && /opt/conda/bin/mamba clean -a -y \
    && /opt/conda/bin/conda clean -a -y \
    && rm -rf /opt/conda/pkgs/* /root/.cache /tmp/* /var/tmp/*

ENV CONDA_DEFAULT_ENV=${ENV_NAME}
ENV CONDA_PREFIX=/opt/conda/envs/${ENV_NAME}
ENV PATH=/opt/conda/envs/${ENV_NAME}/bin:/opt/conda/bin:$PATH

CMD ["bash"]
