FROM ghcr.io/bdrd-genomics/allinone-conda-base:1.0.2

SHELL ["/bin/bash", "-lc"]

COPY environment.mmseqs2.yml /tmp/environment.yml

RUN /opt/conda/bin/mamba env create -f /tmp/environment.yml && \
    /opt/conda/bin/conda clean -a -y

ENV CONDA_DEFAULT_ENV=mmseqs2
ENV CONDA_PREFIX=/opt/conda/envs/mmseqs2
ENV PATH=/opt/conda/envs/mmseqs2/bin:/opt/conda/bin:$PATH

CMD ["bash"]
