#!/usr/bin/env bash

set -euo pipefail

###############################################################################
# All-In-One full-test database setup
#
# REAL databases:
#   - CheckM
#   - CheckM2
#   - CheckV
#   - BUSCO bacteria_odb12.2
#   - AMRFinderPlus
#   - MEGAN 7 mapping databases
#
# SYNTHETIC / TOY databases:
#   - BLAST nucleotide
#   - BLAST protein
#   - DIAMOND protein
#   - MMseqs2 nucleotide
#   - MMseqs2 protein
#   - Kraken2
#   - lightweight taxonomy resources
#
# The protein databases use tests/data/reference/test_protein.faa, generated by
# setup_test_data.sh. Its coding sequence is embedded in test_reference.fasta,
# guaranteeing BLASTX/DIAMOND hits during the integration test.
#
# Usage:
#   ./scripts/setup_test_databases.sh
#   ./scripts/setup_test_databases.sh /path/to/test_databases
###############################################################################

###############################################################################
# Paths and images
###############################################################################

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_ROOT="${1:-${ROOT_DIR}/tests/databases}"
TOY_DIR="${DB_ROOT}/toy"
TEST_PROTEIN_FASTA="${ROOT_DIR}/tests/data/reference/test_protein.faa"

GHCR_ROOT="ghcr.io/bdrd-genomics"
BLAST_IMAGE="${AIO_BLAST_IMAGE:-${GHCR_ROOT}/allinone-blast:latest}"
DIAMOND_IMAGE="${AIO_DIAMOND_IMAGE:-${GHCR_ROOT}/allinone-diamond:latest}"
MMSEQS_IMAGE="${AIO_MMSEQS_IMAGE:-${GHCR_ROOT}/allinone-mmseqs2:latest}"
KRAKEN_IMAGE="${AIO_KRAKEN_IMAGE:-${GHCR_ROOT}/allinone-kraken2:latest}"
MEGAN_IMAGE="${AIO_MEGAN_IMAGE:-${GHCR_ROOT}/allinone-megan:latest}"

TEST_DB_ENV="aio_test_databases"
TEST_DB_ENV_FILE="${ROOT_DIR}/env/test_databases.yml"

mkdir -p "${DB_ROOT}" "${TOY_DIR}/fasta"

###############################################################################
# Helpers
###############################################################################

have_command() {
    command -v "$1" >/dev/null 2>&1
}

section() {
    echo
    echo "============================================================"
    echo " $1"
    echo "============================================================"
}

download_file() {
    local url="$1"
    local output="$2"

    mkdir -p "$(dirname "${output}")"

    if have_command wget; then
        wget --continue -O "${output}" "${url}"
    elif have_command curl; then
        if [[ -f "${output}" ]]; then
            curl -L --fail --retry 3 -C - -o "${output}" "${url}"
        else
            curl -L --fail --retry 3 -o "${output}" "${url}"
        fi
    else
        echo "ERROR: Neither wget nor curl is available."
        exit 1
    fi
}

extract_zip() {
    local archive="$1"
    local destination="$2"

    mkdir -p "${destination}"

    if have_command unzip; then
        unzip -o "${archive}" -d "${destination}"
    elif [[ "${BUILD_BACKEND:-}" == "docker" ]]; then
        docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            -v "${DB_ROOT}:${DB_ROOT}" \
            "${MEGAN_IMAGE}" \
            unzip -o "${archive}" -d "${destination}"
    elif [[ "${BUILD_BACKEND:-}" == "conda" ]]; then
        conda run \
            -n "${TEST_DB_ENV}" \
            python -m zipfile -e "${archive}" "${destination}"
    else
        echo "ERROR: Unable to extract ZIP archive: ${archive}"
        exit 1
    fi
}

place_mdb_at_root() {
    local root="$1"
    local filename="$2"
    local expected="${root}/${filename}"

    if [[ -s "${expected}" ]]; then
        return 0
    fi

    local found
    found="$(find "${root}" -type f -name "${filename}" -print -quit)"

    if [[ -z "${found}" ]]; then
        echo "ERROR: ${filename} was not found under ${root} after extraction."
        exit 1
    fi

    if [[ "${found}" != "${expected}" ]]; then
        mv "${found}" "${expected}"
    fi
}

remove_mmseqs_prefix() {
    local prefix="$1"
    rm -f \
        "${prefix}" \
        "${prefix}.dbtype" \
        "${prefix}.index" \
        "${prefix}.lookup" \
        "${prefix}.source" \
        "${prefix}_h" \
        "${prefix}_h.dbtype" \
        "${prefix}_h.index" \
        2>/dev/null || true
}

###############################################################################
# Header and prerequisite
###############################################################################

echo "============================================================"
echo " All-In-One test database setup"
echo "============================================================"
echo
echo "Repository : ${ROOT_DIR}"
echo "Database   : ${DB_ROOT}"
echo

if [[ ! -s "${TEST_PROTEIN_FASTA}" ]]; then
    echo "ERROR: Synthetic test protein does not exist:"
    echo "  ${TEST_PROTEIN_FASTA}"
    echo
    echo "Run this first:"
    echo "  ./scripts/setup_test_data.sh"
    exit 1
fi

###############################################################################
# Detect Docker / Conda
###############################################################################

BUILD_BACKEND=""
section "Detecting test database build environment"

if have_command docker && docker info >/dev/null 2>&1; then
    BUILD_BACKEND="docker"

    echo "Docker detected and usable."
    echo
    echo "Images:"
    echo "  BLAST   : ${BLAST_IMAGE}"
    echo "  DIAMOND : ${DIAMOND_IMAGE}"
    echo "  MMseqs2 : ${MMSEQS_IMAGE}"
    echo "  Kraken2 : ${KRAKEN_IMAGE}"
    echo "  MEGAN   : ${MEGAN_IMAGE}"

    section "Pulling All-In-One database builder images"
    docker pull "${BLAST_IMAGE}"
    docker pull "${DIAMOND_IMAGE}"
    docker pull "${MMSEQS_IMAGE}"
    docker pull "${KRAKEN_IMAGE}"
    docker pull "${MEGAN_IMAGE}"

elif have_command conda; then
    BUILD_BACKEND="conda"

    echo "Docker unavailable; using Conda environment ${TEST_DB_ENV}."

    if [[ ! -f "${TEST_DB_ENV_FILE}" ]]; then
        echo "ERROR: Conda environment definition does not exist:"
        echo "  ${TEST_DB_ENV_FILE}"
        exit 1
    fi

    if conda env list | awk '{print $1}' | grep -qx "${TEST_DB_ENV}"; then
        echo "Conda environment already exists; skipping creation."
    else
        if have_command mamba; then
            mamba env create -f "${TEST_DB_ENV_FILE}"
        else
            conda env create -f "${TEST_DB_ENV_FILE}"
        fi
    fi

else
    echo "ERROR: Docker or Conda/Mamba is required."
    exit 1
fi

run_db_tool() {
    local image="$1"
    shift

    if [[ "${BUILD_BACKEND}" == "docker" ]]; then
        docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            -v "${ROOT_DIR}:${ROOT_DIR}" \
            -v "${DB_ROOT}:${DB_ROOT}" \
            -w "${ROOT_DIR}" \
            "${image}" \
            "$@"
    else
        conda run -n "${TEST_DB_ENV}" "$@"
    fi
}

###############################################################################
# Verify database build tools
###############################################################################

section "Checking database build software"
run_db_tool "${BLAST_IMAGE}" makeblastdb -version >/dev/null
run_db_tool "${DIAMOND_IMAGE}" diamond version >/dev/null
run_db_tool "${MMSEQS_IMAGE}" mmseqs version >/dev/null
run_db_tool "${KRAKEN_IMAGE}" kraken2-build --help >/dev/null 2>&1 || true

echo "Database build environment is ready."

###############################################################################
# Real databases
###############################################################################

section "Installing real test databases"

if [[ ! -x "${ROOT_DIR}/scripts/download_databases.sh" ]]; then
    echo "ERROR: Database installer is missing or not executable:"
    echo "  ${ROOT_DIR}/scripts/download_databases.sh"
    exit 1
fi

echo
echo "[1/6] Installing CheckM database"
"${ROOT_DIR}/scripts/download_databases.sh" \
    --db-root "${DB_ROOT}" \
    --db checkm

echo
echo "[2/6] Installing CheckM2 database"
"${ROOT_DIR}/scripts/download_databases.sh" \
    --db-root "${DB_ROOT}" \
    --db checkm2

echo
echo "[3/6] Installing CheckV database"
"${ROOT_DIR}/scripts/download_databases.sh" \
    --db-root "${DB_ROOT}" \
    --db checkv

###############################################################################
# BUSCO
###############################################################################

echo
echo "[4/6] Installing BUSCO database"

BUSCO_ROOT="${DB_ROOT}/busco"
BUSCO_LINEAGE="bacteria_odb12.2"
BUSCO_ARCHIVE="bacteria_odb12.2.2026-05-22.tar.gz"
BUSCO_URL="https://busco-data.ezlab.org/v6/data/lineages/${BUSCO_ARCHIVE}"
BUSCO_DIR="${BUSCO_ROOT}/${BUSCO_LINEAGE}"
BUSCO_ARCHIVE_PATH="${BUSCO_ROOT}/${BUSCO_ARCHIVE}"

mkdir -p "${BUSCO_ROOT}"

if [[ -d "${BUSCO_DIR}" ]]; then
    echo "BUSCO database already installed: ${BUSCO_DIR}"
else
    if [[ ! -s "${BUSCO_ARCHIVE_PATH}" ]]; then
        download_file "${BUSCO_URL}" "${BUSCO_ARCHIVE_PATH}"
    else
        echo "BUSCO archive already exists; skipping download."
    fi

    if ! tar -tzf "${BUSCO_ARCHIVE_PATH}" >/dev/null 2>&1; then
        echo "ERROR: BUSCO archive is invalid: ${BUSCO_ARCHIVE_PATH}"
        exit 1
    fi

    tar -xzf "${BUSCO_ARCHIVE_PATH}" -C "${BUSCO_ROOT}"

    if [[ ! -d "${BUSCO_DIR}" ]]; then
        echo "ERROR: BUSCO extraction finished but ${BUSCO_DIR} was not found."
        ls -lah "${BUSCO_ROOT}"
        exit 1
    fi
fi

###############################################################################
# AMRFinderPlus
###############################################################################

echo
echo "[5/6] Installing AMRFinderPlus database"
"${ROOT_DIR}/scripts/download_databases.sh" \
    --db-root "${DB_ROOT}" \
    --db amrfinderplus

###############################################################################
# MEGAN 7 mapping databases
###############################################################################

echo
echo "[6/6] Installing MEGAN 7 mapping databases"

MEGAN_ROOT="${DB_ROOT}/megan"
MEGAN_NR_ARCHIVE="${MEGAN_ROOT}/megan-nr-r2.zip"
MEGAN_NR_DB="${MEGAN_ROOT}/megan-nr-r2.mdb"
MEGAN_NR_URL="https://software-ab.cs.uni-tuebingen.de/download/megan7/megan-nr-r2.zip"
MEGAN_GENOME_ARCHIVE="${MEGAN_ROOT}/megan-genome-r1.zip"
MEGAN_GENOME_DB="${MEGAN_ROOT}/megan-genome-r1.mdb"
MEGAN_GENOME_URL="https://software-ab.cs.uni-tuebingen.de/download/megan7/megan-genome-r1.zip"

mkdir -p "${MEGAN_ROOT}"

if [[ -s "${MEGAN_NR_DB}" ]]; then
    echo "MEGAN NCBI-nr mapping database already installed."
else
    if [[ ! -s "${MEGAN_NR_ARCHIVE}" ]]; then
        download_file "${MEGAN_NR_URL}" "${MEGAN_NR_ARCHIVE}"
    fi
    extract_zip "${MEGAN_NR_ARCHIVE}" "${MEGAN_ROOT}"
    place_mdb_at_root "${MEGAN_ROOT}" "megan-nr-r2.mdb"
fi

if [[ -s "${MEGAN_GENOME_DB}" ]]; then
    echo "MEGAN genomic mapping database already installed."
else
    if [[ ! -s "${MEGAN_GENOME_ARCHIVE}" ]]; then
        download_file "${MEGAN_GENOME_URL}" "${MEGAN_GENOME_ARCHIVE}"
    fi
    extract_zip "${MEGAN_GENOME_ARCHIVE}" "${MEGAN_ROOT}"
    place_mdb_at_root "${MEGAN_ROOT}" "megan-genome-r1.mdb"
fi

if [[ ! -s "${MEGAN_NR_DB}" ]] || [[ ! -s "${MEGAN_GENOME_DB}" ]]; then
    echo "ERROR: One or more MEGAN mapping databases are missing."
    exit 1
fi

echo "MEGAN mapping databases are ready:"
echo "  ${MEGAN_NR_DB}"
echo "  ${MEGAN_GENOME_DB}"

###############################################################################
# Toy nucleotide reference
###############################################################################

section "Creating toy nucleotide reference"

TOY_NT_FASTA="${TOY_DIR}/fasta/toy_nt.fna"

cat > "${TOY_NT_FASTA}" <<'FASTA'
>toy_bacterium_1
ATGCGTACGTTAGCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCG
ATCGTAGCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCGATCGTA
GCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCGATCGTAGCTAGC
>toy_bacterium_2
ATGGCTGCTGCTGATCGATCGTAGCGATCGATGCTAGCTAGCATCGATCGTAGCTAGCATCGATGC
TAGCTAGCATCGATCGTAGCTAGCTAGCATCGATCGATGCTAGCTAGCATCGATCGTAGCTAGCAT
CGATGCTAGCTAGCATCGATCGTAGCTAGCATCGATGCTAGCTAGCATCGATCGTAGCTAGCATCG
>toy_virus_1
ATGAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAA
GGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTT
CCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAAGGGTTTCCCAAA
FASTA

###############################################################################
# Toy protein reference linked to synthetic test reads
###############################################################################

section "Preparing toy protein reference"

TOY_NR_FASTA="${TOY_DIR}/fasta/toy_nr.faa"
cp "${TEST_PROTEIN_FASTA}" "${TOY_NR_FASTA}"

echo "Toy protein FASTA: ${TOY_NR_FASTA}"
head -n 1 "${TOY_NR_FASTA}"

###############################################################################
# BLAST databases
###############################################################################

section "Building toy BLAST databases"

mkdir -p "${DB_ROOT}/blast/nt" "${DB_ROOT}/blast/nr"

if [[ ! -f "${DB_ROOT}/blast/nt/nt.nsq" ]] && \
   [[ ! -f "${DB_ROOT}/blast/nt/nt.ndb" ]]; then
    run_db_tool \
        "${BLAST_IMAGE}" \
        makeblastdb \
        -in "${TOY_NT_FASTA}" \
        -dbtype nucl \
        -parse_seqids \
        -out "${DB_ROOT}/blast/nt/nt"
else
    echo "Toy BLAST nucleotide database already exists; skipping."
fi

BLAST_NR_MARKER="${DB_ROOT}/blast/nr/nr.psq"
if [[ ! -f "${BLAST_NR_MARKER}" ]] || [[ "${TOY_NR_FASTA}" -nt "${BLAST_NR_MARKER}" ]]; then
    echo "Building/rebuilding toy BLAST protein database."
    rm -f "${DB_ROOT}/blast/nr/nr."* 2>/dev/null || true
    run_db_tool \
        "${BLAST_IMAGE}" \
        makeblastdb \
        -in "${TOY_NR_FASTA}" \
        -dbtype prot \
        -parse_seqids \
        -out "${DB_ROOT}/blast/nr/nr"
else
    echo "Toy BLAST protein database is current; skipping."
fi

###############################################################################
# DIAMOND database
###############################################################################

section "Building toy DIAMOND database"

mkdir -p "${DB_ROOT}/diamond"
DIAMOND_DB="${DB_ROOT}/diamond/nr.dmnd"

if [[ ! -f "${DIAMOND_DB}" ]] || [[ "${TOY_NR_FASTA}" -nt "${DIAMOND_DB}" ]]; then
    echo "Building/rebuilding toy DIAMOND database."
    rm -f "${DIAMOND_DB}"
    run_db_tool \
        "${DIAMOND_IMAGE}" \
        diamond makedb \
        --in "${TOY_NR_FASTA}" \
        --db "${DB_ROOT}/diamond/nr"
else
    echo "Toy DIAMOND database is current; skipping."
fi

###############################################################################
# MMseqs2 databases
###############################################################################

section "Building toy MMseqs2 databases"

mkdir -p "${DB_ROOT}/mmseqs"

if [[ ! -f "${DB_ROOT}/mmseqs/nt" ]] || \
   [[ ! -f "${DB_ROOT}/mmseqs/nt.dbtype" ]]; then
    remove_mmseqs_prefix "${DB_ROOT}/mmseqs/nt"
    run_db_tool \
        "${MMSEQS_IMAGE}" \
        mmseqs createdb \
        "${TOY_NT_FASTA}" \
        "${DB_ROOT}/mmseqs/nt"
else
    echo "Toy MMseqs nucleotide database already exists; skipping."
fi

MMSEQS_NR_DB="${DB_ROOT}/mmseqs/nr"
if [[ ! -f "${MMSEQS_NR_DB}" ]] || \
   [[ ! -f "${MMSEQS_NR_DB}.dbtype" ]] || \
   [[ "${TOY_NR_FASTA}" -nt "${MMSEQS_NR_DB}" ]]; then
    echo "Building/rebuilding toy MMseqs protein database."
    remove_mmseqs_prefix "${MMSEQS_NR_DB}"
    run_db_tool \
        "${MMSEQS_IMAGE}" \
        mmseqs createdb \
        "${TOY_NR_FASTA}" \
        "${MMSEQS_NR_DB}"
else
    echo "Toy MMseqs protein database is current; skipping."
fi

###############################################################################
# Tiny Kraken2 database
###############################################################################

section "Building tiny Kraken2 database"

KRAKEN_DB="${DB_ROOT}/kraken2/test"
mkdir -p "${KRAKEN_DB}"

if [[ -f "${KRAKEN_DB}/hash.k2d" ]] && \
   [[ -f "${KRAKEN_DB}/opts.k2d" ]] && \
   [[ -f "${KRAKEN_DB}/taxo.k2d" ]]; then
    echo "Toy Kraken2 database already exists; skipping."
else
    mkdir -p "${KRAKEN_DB}/taxonomy"

    cat > "${KRAKEN_DB}/taxonomy/nodes.dmp" <<'EOF_NODES'
1	|	1	|	no rank	|		|	0	|	0	|	11	|	1	|	0	|	1	|	0	|		|
2	|	1	|	superkingdom	|		|	0	|	0	|	11	|	1	|	0	|	1	|	0	|		|
562	|	2	|	species	|		|	0	|	0	|	11	|	1	|	0	|	1	|	0	|		|
EOF_NODES

    cat > "${KRAKEN_DB}/taxonomy/names.dmp" <<'EOF_NAMES'
1	|	root	|		|	scientific name	|
2	|	Bacteria	|		|	scientific name	|
562	|	Escherichia coli	|		|	scientific name	|
EOF_NAMES

    KRAKEN_FASTA="${TOY_DIR}/fasta/kraken_test.fna"
    cat > "${KRAKEN_FASTA}" <<'EOF_KRAKEN'
>kraken:taxid|562|toy_ecoli
ATGCGTACGTTAGCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCG
ATCGTAGCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCGATCGTA
GCTAGCTACGATCGATCGTAGCTAGCTACGATCGATCGTAGCTAGCATCGATCGATCGTAGCTAGC
EOF_KRAKEN

    run_db_tool \
        "${KRAKEN_IMAGE}" \
        kraken2-build \
        --add-to-library "${KRAKEN_FASTA}" \
        --db "${KRAKEN_DB}"

    run_db_tool \
        "${KRAKEN_IMAGE}" \
        kraken2-build \
        --build \
        --db "${KRAKEN_DB}" \
        --threads 2

    run_db_tool \
        "${KRAKEN_IMAGE}" \
        kraken2-build \
        --clean \
        --db "${KRAKEN_DB}"

    if [[ ! -f "${KRAKEN_DB}/hash.k2d" ]]; then
        echo "ERROR: Kraken2 database build failed."
        exit 1
    fi
fi

###############################################################################
# Lightweight taxonomy resource
###############################################################################

section "Creating simple taxonomy resources"

mkdir -p "${DB_ROOT}/taxdb"
cat > "${DB_ROOT}/taxdb/test_accession_taxid.tsv" <<'EOF_TAX'
accession	taxid
NP_414543.1	562
toy_bacterium_1	562
toy_bacterium_2	562
toy_virus_1	10239
EOF_TAX

###############################################################################
# Information marker
###############################################################################

cat > "${DB_ROOT}/TEST_DATABASE_INFO.txt" <<EOF_INFO
All-In-One lightweight/full functional test database

Generated:
$(date)

Database root:
${DB_ROOT}

Build backend:
${BUILD_BACKEND}

Real databases:
 - CheckM
 - CheckM2
 - CheckV
 - BUSCO
 - AMRFinderPlus
 - MEGAN 7 NCBI-nr mapping database
 - MEGAN 7 genomic mapping database

Synthetic databases:
 - BLAST nucleotide
 - BLAST protein generated from tests/data/reference/test_protein.faa
 - DIAMOND protein generated from tests/data/reference/test_protein.faa
 - MMseqs2 nucleotide
 - MMseqs2 protein generated from tests/data/reference/test_protein.faa
 - Kraken2
 - lightweight taxonomy resources

Test protein accession:
 NP_414543.1

These databases are intended only for pipeline functional testing.
They MUST NOT be used for biological interpretation.
EOF_INFO

###############################################################################
# Finished
###############################################################################

echo
echo "============================================================"
echo " Test database setup complete"
echo "============================================================"
echo
echo "Database root:"
echo "  ${DB_ROOT}"
echo
echo "MEGAN NCBI-nr mapping database:"
echo "  ${MEGAN_NR_DB}"
echo
echo "Toy DIAMOND database:"
echo "  ${DB_ROOT}/diamond/nr.dmnd"
echo
echo "The databases can now be used by the full test."
echo
