name: aio_assembly
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - spades
  - unicycler
  - dragonflye
  - flye
  - raven-assembler
  - medaka
  - racon
  - polypolish
  - minimap2
  - samtools
  - seqkit
  - pigz
